version: '2'
services:

  api:
    image: python:2.7.12
    container_name: "halcyon_backend_api"
    build: .
    command: "flask run --host=0.0.0.0"
    ports: 
      - "8000:5000"
    volumes:
      - "./app:/halcyon"
    links:
      - db
    env_file: .env
    
  db:
    image: postgres:9.6.1
    container_name: "halcyon_backend_db"
    env_file: .env
  